[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
name = "qnmsc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "diffaaable",
    "ipykernel>=6.29.5",
    "ipympl>=0.9.6",
    "jax>=0.5.0",
    "jpu>=0.0.4",
    "matplotlib>=3.10.0",
    "pyqt6>=6.8.1",
    "scienceplots>=2.1.1",
    "staaax>=0.2.0",
    "tqdm>=4.67.1",
    "treams",
]

[tool.uv.sources]
diffaaable = { git = "ssh://git@github.com/jan-david-fischbach/diffaaable", rev = "subdivide_adaptive-1" }
treams = { url = "https://github.com/jan-david-fischbach/jat/releases/download/v0.5.0/treams-0.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" }
